// Chapter 7: The Rational and Jordan Forms (Sections 40-44)
// Based on Hoffman & Kunze Chapter 7
import type { QuizQuestion } from './types';

// Section 40: Cyclic Subspaces and Annihilators
export const section40Quiz: QuizQuestion[] = [
  {
    id: 's40-q1',
    question: 'The cyclic subspace generated by v under T is:',
    options: ['{v}', 'span{v, Tv, T²v, ...}', 'V', 'ker(T)'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The T-cyclic subspace generated by v is Z(v;T) = span{v, Tv, T²v, ...}.'
  },
  {
    id: 's40-q2',
    question: 'The T-annihilator of v is:',
    options: ['A vector', 'The monic polynomial of least degree with p(T)v = 0', 'The characteristic polynomial', 'Zero'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'The T-annihilator is the minimal monic polynomial annihilating v under T.'
  },
  {
    id: 's40-q3',
    question: 'If v is a cyclic vector for T on V, then:',
    options: ['V = span{v}', 'V = Z(v;T)', 'v = 0', 'T = I'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'A cyclic vector generates all of V under repeated application of T.'
  }
];

// Section 41: Cyclic Decompositions and the Rational Form
export const section41Quiz: QuizQuestion[] = [
  {
    id: 's41-q1',
    question: 'The rational canonical form exists for:',
    options: ['Only diagonalizable operators', 'Only nilpotent operators', 'All linear operators', 'Only invertible operators'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'Every linear operator has a rational canonical form over any field.'
  },
  {
    id: 's41-q2',
    question: 'The companion matrix of polynomial p(x) = xⁿ + aₙ₋₁xⁿ⁻¹ + ... + a₀ has:',
    options: ['All zeros', 'Ones on superdiagonal and -aᵢ in last column', 'Diagonal entries only', 'Random entries'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'The companion matrix has 1s on the subdiagonal (or superdiagonal) and coefficients in one row/column.'
  },
  {
    id: 's41-q3',
    question: 'The rational form is block diagonal with blocks that are:',
    options: ['Identity matrices', 'Companion matrices', 'Jordan blocks', 'Zero matrices'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Rational form consists of companion matrices for the invariant factors.'
  },
  {
    id: 's41-q4',
    question: 'Two matrices are similar iff they have:',
    options: ['The same trace', 'The same determinant', 'The same invariant factors', 'The same size'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'Matrices are similar iff they have the same invariant factors (equivalently, same rational form).'
  }
];

// Section 42: The Jordan Form
export const section42Quiz: QuizQuestion[] = [
  {
    id: 's42-q1',
    question: 'Jordan canonical form exists when:',
    options: ['Always', 'The characteristic polynomial splits over F', 'T is diagonalizable', 'F = ℝ'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Jordan form exists iff all eigenvalues are in F (characteristic polynomial splits).'
  },
  {
    id: 's42-q2',
    question: 'A Jordan block Jₖ(λ) is a k × k matrix with:',
    options: ['λ on diagonal, 1s on superdiagonal', 'All entries equal to λ', 'λ everywhere', 'Only diagonal λ'],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'Jordan block: λ on diagonal, 1s just above diagonal, zeros elsewhere.'
  },
  {
    id: 's42-q3',
    question: 'If A has Jordan form with blocks of sizes 3, 2, 1 for eigenvalue λ, the geometric multiplicity of λ is:',
    options: ['6', '3', '1', 'Undefined'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Geometric multiplicity = number of Jordan blocks for that eigenvalue.'
  },
  {
    id: 's42-q4',
    question: 'A is diagonalizable iff all Jordan blocks have size:',
    options: ['n', '2', '1', '0'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Diagonalizable means all Jordan blocks are 1 × 1 (just eigenvalues on diagonal).'
  }
];

// Section 43: Computation of Invariant Factors
export const section43Quiz: QuizQuestion[] = [
  {
    id: 's43-q1',
    question: 'The Smith normal form of a matrix over F[x] has:',
    options: ['All entries in F', 'Diagonal polynomial entries dividing each other', 'Random polynomials', 'Only constants'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Smith form: diagonal d₁(x), ..., dₖ(x) with dᵢ | dᵢ₊₁.'
  },
  {
    id: 's43-q2',
    question: 'Elementary divisors are obtained by:',
    options: ['Adding invariant factors', 'Factoring invariant factors into prime powers', 'Multiplying eigenvalues', 'Computing determinant'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Elementary divisors are the prime power factors of the invariant factors.'
  },
  {
    id: 's43-q3',
    question: 'Two matrices over F have the same Jordan form (over algebraic closure) iff:',
    options: ['They are equal', 'They have the same elementary divisors', 'They have the same size', 'They commute'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Elementary divisors determine the Jordan form (once eigenvalues are in the field).'
  }
];

// Section 44: Summary; Semi-Simple Operators
export const section44Quiz: QuizQuestion[] = [
  {
    id: 's44-q1',
    question: 'A semi-simple operator is:',
    options: ['Nilpotent', 'Diagonalizable (over algebraic closure)', 'The identity', 'Not well-defined'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Semi-simple = diagonalizable (over an algebraically closed field).'
  },
  {
    id: 's44-q2',
    question: 'Every operator T can be uniquely written as T = S + N where:',
    options: ['S is symmetric, N is skew', 'S is semi-simple, N is nilpotent, SN = NS', 'S = N', 'S + N = I'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Jordan decomposition: T = S + N with S semi-simple, N nilpotent, and they commute.'
  },
  {
    id: 's44-q3',
    question: 'The semi-simple and nilpotent parts of T are:',
    options: ['Always zero', 'Polynomials in T', 'Not related to T', 'Inverses of each other'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'S and N can both be expressed as polynomials in T.'
  }
];

// Chapter 7 Comprehensive Quiz
export const chapter07Quiz: QuizQuestion[] = [
  {
    id: 'ch07-q1',
    question: 'The Jordan form is unique up to:',
    options: ['Similarity', 'Permutation of blocks', 'Nothing (completely unique)', 'Scalar multiplication'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Jordan form is unique up to ordering of the Jordan blocks.'
  },
  {
    id: 'ch07-q2',
    question: 'The largest invariant factor equals:',
    options: ['The characteristic polynomial', 'The minimal polynomial', 'The determinant', 'The trace'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'The last (largest) invariant factor is the minimal polynomial.'
  },
  {
    id: 'ch07-q3',
    question: 'The product of all invariant factors equals:',
    options: ['The minimal polynomial', 'The characteristic polynomial', '1', 'The trace'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'The product of invariant factors equals the characteristic polynomial.'
  },
  {
    id: 'ch07-q4',
    question: 'An n × n nilpotent matrix can have Jordan blocks of size at most:',
    options: ['1', 'n', 'n/2', '2'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'A nilpotent has only eigenvalue 0; blocks can be as large as n (for a cyclic nilpotent).'
  },
  {
    id: 'ch07-q5',
    question: 'The number of 1s above the diagonal in Jordan form equals:',
    options: ['n', 'n - (geometric multiplicity summed over eigenvalues)', 'The trace', '0'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '1s above diagonal = n - (number of Jordan blocks) = n - Σ(geometric multiplicities).'
  },
  {
    id: 'ch07-q6',
    question: 'Companion matrices are always:',
    options: ['Diagonal', 'Symmetric', 'Cyclic (have a cyclic vector)', 'Nilpotent'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'A companion matrix has the standard basis vector e₁ as a cyclic vector.'
  },
  {
    id: 'ch07-q7',
    question: 'If T has Jordan form diag(J₂(λ), J₁(λ)), then dim(ker(T - λI)) equals:',
    options: ['1', '2', '3', '0'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Geometric multiplicity = number of blocks = 2.'
  },
  {
    id: 'ch07-q8',
    question: 'The rational form is defined over:',
    options: ['Only ℂ', 'Only algebraically closed fields', 'Any field', 'Only ℝ'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Rational canonical form exists over any field (no splitting required).'
  },
  {
    id: 'ch07-q9',
    question: 'Matrices with the same characteristic polynomial:',
    options: ['Are always similar', 'May not be similar', 'Have the same Jordan form', 'Commute'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Same characteristic polynomial doesn\'t imply similarity (need same invariant factors).'
  },
  {
    id: 'ch07-q10',
    question: 'For an n × n matrix, the sum of sizes of all Jordan blocks equals:',
    options: ['The rank', 'The trace', 'n', 'The determinant'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Total size of Jordan blocks = dimension of the space = n.'
  }
];
